provider "aws" {
  region = "eu-west-1"
}

terraform {
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.6.0"
    }
  }

  required_version = "~> 1.0"
}

provider "kubectl" {
  host                   = "https://813AFD3E4B3EF72640F51C6CE71D6AC5.gr7.eu-west-1.eks.amazonaws.com" 
  cluster_ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1Ea3dNakUyTWpReU9Wb1hEVE16TURnek1ERTJNalF5T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDdDCmVadElVL29rMjdVSXpteGE2OWM3N1gxSWlqemZVSVBnOUFwNTkvZ2NvbUtkY1NqdzlWWTdvRlNCbmdYZUpzZnYKekhHQURMbGgxeHA2OWg0bExOWGg1MnZaWmdEU1pFcUpmWGlUL0hlZ0YrU0Y0TkpIaEdrYTBXWjIxYXJNVnRJdgpTelM1dEJLM0lBcERqbGcyRm9XdXRDRGJVMWMwdy9JcEVKQmZOcHpaV3JJSFhmZ2Zxbk9Rb3QvaTNCcGt2ZFpFCitZSXc3OXdlb2VGRy9TbFliNTN2L0VsbGluZi9nVmdHbm0xRXExa0FPMGZ2Y2swZUFCUjAzU0dWcUg3d3p6L0MKS0lTS0c3cXk2TWphVGo0SVZXNWdSMWpEWHBuOUI4Sm9VNS9HZG85Y09iTXVnMTk1eUZrRy80aWt4OHNrNUcvMQpOVnRMK0xHNVo4Rm1KNGJtdzZFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKblgwUTI5M2dURk9WNzBNbWliMXQ4SlRNQXlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSWl0ZTh4bDYrS21uSjIxdmxLMApFaUxDTnVjZEtTR3lRNEVwdzBQeFB4OUpFYWtKSHNSWHhYVk1LYzBMMklQWTREMkZJT2RhdDIzNEhkckdtbXhGCktJSVYxYlpwU2RTNWRZQmw4ZTlkSG8wSjA5YmFBa3VEUHNGVUJsT1M3ZHl0WUdZNmJuaTc3V1Y1dUo3VG03UFMKalovQ0wvTmNFMVJlaEx1V0Z3dllxeDRET2F1Y1daNUdlcU1sclE3ZEhaaXNnY3NsUHNZT3ZaZkRBbmZlM0gyTQpNZEV4cjBYWS9HQUVVWTNnTSsza0hMSFVsQnI3M1FoWHBlZHo4bks5dXJzQ2dGTTAya3NFeXVleWhxS3JhZUJNCkloZkpkMDQyRTRkbzZxamhMZGNlblZHV0VwYTludkcrT1B0anpCK1FtWkFuallDSmVVTVhmUUhVaGgyVTRpSngKWjdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", "techoutcomes"]
    command     = "aws"
  }
}
