apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: to-ns-tiger-dev
  name: java-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-app
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxpublic.ecr.aws/l6m2t8p7/docker-2048:latestxxxxxxxxxxxxxxxx
        imagePullPolicy: Always
        name: java-app
        ports:
        - containerPort: 80
